### Ir a la pagina principal
http://localhost:3000

### Mostrar todos los productos
GET http://localhost:3000/productos

### Mostrar un producto por id
GET http://localhost:3000/productos/30

### Devuelve los productos que coinciden con el nombre especificado (búsqueda parcial).
GET http://localhost:3000/productos/nombre/aur

### Crear/Agregar un nuevo producto
POST http://localhost:3000/productos/
Content-Type: application/json

{
  "nombre": "Auriculares Gaming",
  "precio": 29.99,
  "categoria": "Accesorios"
}

### Modificar el precio de un producto
PATCH http://localhost:3000/productos/5
Content-Type: application/json

{
  "precio": 39.99
}

### Borrar un producto
DELETE http://localhost:3000/productos/30

