### Ir a la pagina principal
http://localhost:3000

### Mostrar todos los productos
GET http://localhost:3000/productos

### Mostrar un producto por id
GET http://localhost:3000/productos/id/6679d7a9988c9105ee1e2b4c

### Devuelve los productos que coinciden con el nombre especificado (búsqueda parcial).
GET http://localhost:3000/productos/nombre/Moni

### Crear/Agregar un nuevo producto
POST http://localhost:3000/productos/
Content-Type: application/json

{
  "nombre": "Auriculares Gaming",
  "precio": 29.99,
  "categoria": "Accesorios"
}

### Modificar el precio de un producto
PATCH http://localhost:3000/productos/6679d7a9988c9105ee1e2b50
Content-Type: application/json

{
  "precio": 59.99
}

### Borrar un producto
DELETE http://localhost:3000/productos/66905f6e55bb4fc3595ea5cb

### Error por ruta inexistente
GET http://localhost:3000/productos/computacion